# Homebrew formula template. Copy to your tap (homebrew-sqlide/Formula/sqlide.rb) after the
# first PyPI release, then fill url/sha256 and the resource blocks:
#
#   brew update-python-resources sqlide
#
class Sqlide < Formula
  include Language::Python::Virtualenv

  desc "Terminal SQL IDE (DataGrip-like) over JDBC"
  homepage "https://github.com/OWNER/sqlide"
  url "https://files.pythonhosted.org/packages/source/s/sqlide/sqlide-0.1.0.tar.gz"
  sha256 "REPLACE_WITH_SDIST_SHA256"
  license "MIT"

  depends_on "openjdk"
  depends_on "python@3.12"

  # resource blocks (textual, jpype1, openpyxl, httpx, sqlglot, ...) are generated by
  # `brew update-python-resources`

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      sqlide needs a Java runtime; the one from the openjdk formula is used automatically
      when JAVA_HOME is set:
        export JAVA_HOME="#{Formula["openjdk"].opt_prefix}"
      Run `sqlide doctor` to check the setup.
    EOS
  end

  test do
    assert_match "sqlide", shell_output("#{bin}/sqlide --version")
  end
end
