# Homebrew formula template. Copy to your tap (homebrew-sqlide/Formula/sqlide.rb) after the
# first PyPI release, then fill url/sha256 and the resource blocks:
#
#   brew update-python-resources sqlide
#
class Sqlide < Formula
  include Language::Python::Virtualenv

  desc "Terminal SQL IDE (DataGrip-like) over JDBC"
  homepage "https://github.com/XFaIT/sqlide"
  url "https://files.pythonhosted.org/packages/source/s/sqlide/sqlide-0.1.0.tar.gz"
  sha256 "REPLACE_WITH_SDIST_SHA256"
  license "MIT"

  depends_on "openjdk"
  depends_on "python@3.12"

  # resource blocks (textual, jpype1, openpyxl, httpx, sqlglot, ...) are generated by
  # `brew update-python-resources`

  def install
    virtualenv_install_with_resources
    # keg-only openjdk is not on PATH: point sqlide at it
    java_home = if OS.mac?
      Formula["openjdk"].opt_libexec/"openjdk.jdk/Contents/Home"
    else
      Formula["openjdk"].opt_prefix
    end
    rm bin/"sqlide"
    (bin/"sqlide").write_env_script libexec/"bin/sqlide", JAVA_HOME: java_home
  end

  test do
    assert_match "sqlide", shell_output("#{bin}/sqlide --version")
  end
end
