"""Keyword and function names offered by autocomplete, per dialect."""

from __future__ import annotations

COMMON_KEYWORDS = [
    "SELECT",
    "DISTINCT",
    "FROM",
    "WHERE",
    "GROUP",
    "BY",
    "HAVING",
    "ORDER",
    "LIMIT",
    "OFFSET",
    "UNION",
    "ALL",
    "INTERSECT",
    "EXCEPT",
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "FULL",
    "OUTER",
    "CROSS",
    "ON",
    "USING",
    "AS",
    "AND",
    "OR",
    "NOT",
    "IN",
    "IS",
    "NULL",
    "LIKE",
    "BETWEEN",
    "EXISTS",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "ASC",
    "DESC",
    "NULLS",
    "FIRST",
    "LAST",
    "INSERT",
    "INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE",
    "MERGE",
    "RETURNING",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "TABLE",
    "VIEW",
    "INDEX",
    "SCHEMA",
    "SEQUENCE",
    "DATABASE",
    "ADD",
    "COLUMN",
    "CONSTRAINT",
    "PRIMARY",
    "KEY",
    "FOREIGN",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "DEFAULT",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
    "WITH",
    "RECURSIVE",
    "EXPLAIN",
    "TRUE",
    "FALSE",
    "CAST",
    "OVER",
    "PARTITION",
    "ROWS",
    "RANGE",
]

COMMON_FUNCTIONS = [
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "COALESCE",
    "NULLIF",
    "ABS",
    "ROUND",
    "FLOOR",
    "CEIL",
    "LOWER",
    "UPPER",
    "LENGTH",
    "TRIM",
    "SUBSTRING",
    "REPLACE",
    "CONCAT",
    "ROW_NUMBER",
    "RANK",
    "DENSE_RANK",
    "LAG",
    "LEAD",
]

_DIALECT_KEYWORDS = {
    "postgres": "ILIKE RETURNING LATERAL MATERIALIZED VACUUM ANALYZE COPY SERIAL JSONB ARRAY",
    "mysql": "SHOW DESCRIBE USE ENGINE AUTO_INCREMENT REPLACE IGNORE STRAIGHT_JOIN",
    "clickhouse": "FINAL SAMPLE PREWHERE ENGINE SETTINGS FORMAT ARRAY ATTACH DETACH OPTIMIZE",
    "oracle": "ROWNUM DUAL CONNECT PRIOR MINUS FETCH NEXT ONLY SYSDATE",
    "mssql": "TOP GO NOLOCK IDENTITY EXEC PROCEDURE DECLARE",
    "sqlite": "PRAGMA AUTOINCREMENT VACUUM GLOB",
}

_DIALECT_FUNCTIONS = {
    "postgres": "NOW GENERATE_SERIES STRING_AGG ARRAY_AGG TO_CHAR DATE_TRUNC JSONB_BUILD_OBJECT",
    "mysql": "NOW IFNULL GROUP_CONCAT DATE_FORMAT CURDATE",
    "clickhouse": "toDate toDateTime toString arrayJoin uniq groupArray now today",
    "oracle": "NVL TO_CHAR TO_DATE SYSDATE DECODE LISTAGG",
    "mssql": "GETDATE ISNULL DATEADD DATEDIFF STRING_AGG",
    "sqlite": "IFNULL DATE DATETIME STRFTIME GROUP_CONCAT",
}


def keywords(dialect: str) -> list[str]:
    return sorted({*COMMON_KEYWORDS, *_DIALECT_KEYWORDS.get(dialect, "").split()})


def functions(dialect: str) -> list[str]:
    return sorted({*COMMON_FUNCTIONS, *_DIALECT_FUNCTIONS.get(dialect, "").split()})
